# 출력되는 로그에 색상 출력
spring:
  data:
    mongodb:
      uri: mongodb://localhost:32768/user
      grid-fs-database: images
  output:
    ansi:
      enabled: always
# 생성되는 로그 파일명
logging:
  file: application.log